name: Run e2e Tests

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    name: Playwright - ${{ matrix.part }}
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Woosmap/wp-store-locator-widget-block' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        part: [ 1, 2, 3, 4, 5, 6, 7, 8 ]
        totalParts: [ 8 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        id: npm-and-build-cache
        with:
          path: |
            node_modules
            ~/.cache
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm deps
        run: |
          npm ci
          npm install -g playwright-cli
          npx playwright install chromium firefox webkit --with-deps
      - name: Install WordPress and start the server
        run: |
          npm run env:start
      - name: Run the tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e -- --shard=${{ matrix.part }}/${{ matrix.totalParts }}

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-playwright-results
          path: artifacts
          retention-days: 1
          if-no-files-found: ignore
